/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#4F46E5",
        primaryLight: "#EEF2FF",
        primaryDark: "#3730A3",
        accent: "#7C3AED",
        background: "#FFFFFF",
        surface: "#F9FAFB",
        surfaceRaised: "#F3F4F6",
        text: "#111827",
        textSecondary: "#6B7280",
        textMuted: "#9CA3AF",
        border: "#E5E7EB",
        borderStrong: "#D1D5DB",
        success: "#10B981",
        successLight: "#ECFDF5",
        warning: "#F59E0B",
        warningLight: "#FFFBEB",
        error: "#EF4444",
        errorLight: "#FEF2F2",
        gold: "#D97706",
        goldLight: "#FEF3C7",
      },
      fontSize: {
        xs: "12px",
        sm: "13px",
        base: "15px",
        lg: "17px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "30px",
        "4xl": "36px",
      },
      height: {
        0.5: "2px",
      },
    },
  },
  plugins: [],
};
